# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!

target 'TYPagerController-ZHScrollViewNestPagerControllerDemo' do

pod 'Masonry', '~> 1.0.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'TYPagerController'

end
